<img src="numpy_fondo.png">

## ¿Qué es?

NumPy es librería Python para trabajar con vectores y matrices por excelencia. Dicho esto, parece claro por qué es necesario
al menos conocerla y saber alguna de sus funcionalidades más importantes.

Es una de las librerías sobre las que se apoya **pandas**, la más relevante a la hora de realizar proyectos *data-science* y
*machine learning* con Python.

## Arrays -  Inicialización

Un **NumPy array**  es una matriz de valores (del mismo tipo) indexada por una tupla de enteros no negativos. 

El número de dimensiones es el rango de la matriz; la forma de una matriz es una tupla de números enteros que dan el tamaño de la matriz a lo largo de cada dimensión.

Podemos inicializarlos de la siguiente forma:

In [2]:
import numpy as np                                      # Importamos la libreria (por convenio se nombra np)

a = np.array([1, 2, 3])                                 # NumPy array de 1 dimensión
print(f'Tipo: {type(a)}')                               # Comprobamos el tipo del objeto recien creado
print(f'Dimensión: {a.shape}')                          # Imprimimos su dimensión
print(f'Valor de la primera posición: {a[0]}')          # Accedemos a la posición 0 
a[0] = 5                                                # Modificamos el valor en la posición 0
print(f'Array actualizado: {a}')  

print()

b = np.array([[1,2,3],[4,5,6]])                         # NumPy array de 2 dimensiones
print(f'Dimensión: {b.shape}')                     
print(f'Valor en la posición (1,0): {b[1, 0]}')   

Tipo: <class 'numpy.ndarray'>
Dimensión: (3,)
Valor de la primera posición: 1
Array actualizado: [5 2 3]

Dimensión: (2, 3)
Valor en la posición (1,0): 4


NumPy ofrece unas funciones de inicialización bastante útiles:

In [7]:
a = np.zeros((2,2))                 # Array de 0s de dimension 2 x 2
print('Matriz de 0s:')              
print(a)

print()

b = np.ones((1,2))                  # Array de 0s de dimension 1 x 2
print('Matriz de 1s:')
print(b)
                      
print()

c = np.full((2,2), 7)               # Array de valores constantes
print('Matriz de valores constantes:')
print(c)
                              
print()
               
d = np.eye(2)                       # Matriz identidad 2 x 2
print('Matriz identidad:') 
print(d)
                               
print()
             
e = np.random.random((2,2))         # Array con valores aleatorios comprendidos entre 0 y 1
print('Matriz de valores aleatorios:')
print(e)
                   

Matriz de 0s:
[[0. 0.]
 [0. 0.]]

Matriz de 1s:
[[1. 1.]]

Matriz de valores constantes:
[[7 7]
 [7 7]]

Matriz identidad:
[[1. 0.]
 [0. 1.]]

Matriz de valores aleatorios:
[[0.72321989 0.99167964]
 [0.15414149 0.985226  ]]


## Indexación

Numpy ofrece varias formas de indexar en matrices.

Slicing: similar a las listas de Python, las matrices numpy se pueden cortar. Al poder tratarse de matrices multidimensionales, debemos especificar la dimensión:


In [15]:
a = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])   # creamos una matriz de 3D
print('a:')
print(a)

print()

b = a[:2, 1:3]       # Nos quedamos con las elementos 1 y 2 de las3 dimensiones                                        
print('b:')
print(b)

print()

c = a[0,1]           # También podemos indexar con enteros (no slicing)
print(f'c: {c}')

print()

d = a[1, :]          # O podemos combinar ambos tipos
print('d:')
print(d)

a:
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]

b:
[[2 3]
 [6 7]]

c: 2

d:
[5 6 7 8]


Indexación por condición: Devuelve un numpy array de *booleanos*: True/False, en aquellas posiciones que cumplan la condición:

In [17]:
a = np.array([[1,2], [3, 4], [5, 6]])
print('a:')
print(a)

print()

b = (a > 3)  # Encuentra las posiciones que tengan valores mayores que 3
             # Devuelve un array de booleanos
print('b:')
print(b)
                    

a:
[[1 2]
 [3 4]
 [5 6]]

b:
[[False False]
 [False  True]
 [ True  True]]


## Data types

Como ya hemos comentado, las matrices NumPy están formadas por elementos del mismo tipo. 
Al inicializar un array, Numpy intenta adivinar el tipo de datos, pero las funciones que construyen matrices generalmente también incluyen un argumento opcional para especificar explícitamente el tipo de datos. Aquí hay un ejemplo:

In [22]:
a = np.array([1, 2])   # NumPy identifica tipo entero
print(f'Tipo de a: {a.dtype}')

print()

b = np.array([1.0, 2.0])   # NumPy identifica tipo float
print(f'Tipo de b: {b.dtype}')    

print()

c = np.array([1.5, 2.7], dtype=np.int64)   # Forzamos conversión a tipo entero
print('c:')
print(c)
print(f'Tipo de c: {c.dtype}')    

print()

d = np.array([1, 2], dtype=np.float)   # Forzamos conversión a tipo float
print('d:')
print(d)
print(f'Tipo de d: {c.dtype}')   

Tipo de a: int32

Tipo de b: float64

c:
[1 2]
Tipo de c: int64

d:
[1. 2.]
Tipo de d: int64


Si quisieramos cambiar el tipo de datos de un numpy array que ya existe, usamos la funcion np.astype()

In [26]:
e = a.astype(np.float)

print(f'Tipo de a: {a.dtype}')
print(f'Tipo de e: {e.dtype}')
print('e:')
print(e)

Tipo de a: int32
Tipo de e: float64
e:
[1. 2.]


## Operaciones

A continuación se muestran ejemplos de operaciones entre vectores, y funciones que ofrece la librería. Todos estos ejemplos se realizan elemento a elemento:

In [24]:
x = np.array([[1,2],[3,4]], dtype=np.float64)
y = np.array([[5,6],[7,8]], dtype=np.float64)

print('x + y :')
print(x + y)

print()

print('x - y :')
print(x - y)

print()

print('x * y :')
print(x * y)

print()

print('x / y :')
print(x / y)

print()

print('np.sqrt(x) :')
print(np.sqrt(x))

x + y :
[[ 6.  8.]
 [10. 12.]]

x - y :
[[-4. -4.]
 [-4. -4.]]

x * y :
[[ 5. 12.]
 [21. 32.]]

x / y :
[[0.2        0.33333333]
 [0.42857143 0.5       ]]

np.sqrt(x) :
[[1.         1.41421356]
 [1.73205081 2.        ]]


## Producto matricial

Para realizar **producto matricial**, NumPy presenta la funcion np.dot(M1, M2)

In [25]:
x = np.array([[1,2],[3,4]])

y = np.array([[5,6],[7,8]])

print('x:')
print(x)

print()

print('y:')
print(y)

print()

print('Producto matricial x,y :')
print(np.dot(x,y))

x:
[[1 2]
 [3 4]]

y:
[[5 6]
 [7 8]]

Producto matricial x,y :
[[19 22]
 [43 50]]


## Funciones estadísticas

Existen todas aquellas funciones estadísticas que se nos puedan venir a la cabeza, un par de ejemplos: 

- **media**:*np.mean()*

- **desviación típica**: *np.std()*


In [46]:
a = np.array([[1,2,3],[4,5,6]])
print('a:')
print(a)

print()

# Se puede especificar sobre que dimensión queremos realizar la operación:

print(f'Media de todos los elementos: {np.mean(a)}') # todos los elementos

print()

print(f'Media sobre el exe de  ordenadas (x): {np.mean(a, axis = 0)}')
                                           
print()
                                           
print(f'Media sobre el eje de abcisas (y): {np.mean(a, axis = 1)}')

a:
[[1 2 3]
 [4 5 6]]

Media de todos los elementos: 3.5

Media sobre el exe de  ordenadas (x): [2.5 3.5 4.5]

Media sobre el eje de abcisas (y): [2. 5.]


## Transposición matricial
Una de las funciones más empleadas cuando trabajamos con matrices es la transposicion: cambiar filas por columnas. En NumPy se realiza tan sencillo como esto:

In [48]:
a = np.array([[1,2,3], [4,5,6]])
print('a:')
print(a)

print()

print('a transpuesta: ')
print(f'{a.T}')

a:
[[1 2 3]
 [4 5 6]]

a transpuesta: 
[[1 4]
 [2 5]
 [3 6]]


## Concatenación matricial
Muchas veces es interesante concatenar matrices, tanto en el eje X como en el eje Y. Se exige que la dimensión de ambas matrices sea la misma. A continuación dos ejemplos:


In [12]:
a = np.array([[1,2,3], [4,5,6]])
b = np.array([[7,8,9]])

e = np.concatenate([a,b], axis = 0)     # Tiene que coincidir el tamaño del eje x

c = np.array([[1,2,3],[4,5,6]])
d = np.array([[7],[8]])

f = np.concatenate([c,d], axis = 1)     # Tiene que coincidir el tamaño del eje y

print('a:')
print(a)

print()

print('b:')
print(b)

print()

print('b concatenado en a por eje x:')
print(e)

print()

print('c:')
print(c)

print()

print('d:')
print(d)

print()

print('d concatenado en c por eje y:')
print(f)



a:
[[1 2 3]
 [4 5 6]]

b:
[[7 8 9]]

b concatenado en a por eje x:
[[1 2 3]
 [4 5 6]
 [7 8 9]]

c:
[[1 2 3]
 [4 5 6]]

d:
[[7]
 [8]]

d concatenado en c por eje y:
[[1 2 3 7]
 [4 5 6 8]]
